DROP TABLE MANCHESTER CASCADE CONSTRAINTS;
DROP TABLE PLAYERS CASCADE CONSTRAINTS;

drop sequence manchester_idno_seq;
create sequence manchester_idno_seq start with 444 increment by 111;



CREATE TABLE MANCHESTER (
	idno number(5) NOT NULL,
	team varchar2(10 char) NOT NULL,
	PRIMARY KEY (idno)
);

CREATE TABLE PLAYERS (
	idno number(5) NOT NULL,
	memberno number(4) NOT NULL,
	backnumber number(2),
	position varchar2(20 char) NOT NULL,
	name varchar2(25 char) NOT NULL,
	nationality varchar2(15 char) NOT NULL,
	dateofjoin date NOT NULL,
	PRIMARY KEY (memberno)
);

insert into MANCHESTER (IDNO,TEAM) values (111,'First team');
insert into MANCHESTER (IDNO,TEAM) values (222,'Reserves');
insert into MANCHESTER (IDNO,TEAM) values (333,'Staff');

Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1111,1,'GK','DAVID DE GEA','SPAIN',to_date('2011/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1112,3,'DF','ERIC BAILLY','IVORY COAST',to_date('2016/06/08','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1113,4,'DF','PHIL JONES','ENGLAND',to_date('2011/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1114,5,'DF','MARCOS ROJO','ARGENTINA',to_date('2014/08/20','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1115,6,'MF','PAUL POGBA','FRANCE',to_date('2016/08/08','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1116,7,'MF','MEMPHIS','NETHERLANDS',to_date('2015/06/12','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1117,8,'MF','JUAN MATA','SPAIN',to_date('2014/01/25','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1118,9,'FW','ZLATAN IBRAHIMOVIC','SWEDEN',to_date('2016/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1119,10,'FW','WAYNE ROONEY','ENGLAND',to_date('2004/08/31','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1120,11,'FW','ANTHONY MARTIAL','FRANCE',to_date('2015/09/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1121,12,'DF','CHRIS SMALLING','ENGLAND',to_date('2010/07/07','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1122,14,'MF','JESSE LINGARD','ENGLAND',to_date('2009/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1123,15,'FW','ADNAN JANUZAJ','BELGIUM',to_date('2011/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1124,16,'MF','MICHAEL CARRICK','ENGLAND',to_date('2006/07/31','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1125,17,'DF','DALEY BLIND','NETHERLANDS',to_date('2014/09/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1126,18,'FW','ASHLEY YOUNG','ENGLAND',to_date('2011/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1127,19,'FW','MARCUS RASHFORD','ENGLAND',to_date('2014/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1128,20,'GK','SERGIO ROMERO','ARGENTINA',to_date('2015/07/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1129,21,'MF','ANDER HERRERA','SPAIN',to_date('2014/06/26','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1130,22,'MF','HENRIKH MKHITARYAN','ARMENIA',to_date('2016/07/06','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1131,23,'DF','LUKE SHAW','ENGALND',to_date('2014/06/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1132,24,'MF','TIMOTHY FOSUMENSAH','NETHERLANDS',to_date('2014/09/02','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1133,25,'DF','ANTONIO VALENCIA','ECUADOR',to_date('2009/06/30','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1134,27,'MF','MAROUANE FELLAINI','BELGIUM',to_date('2013/09/02','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1135,28,'MF','MORGAN SCHNEIDERLIN','FRANCE',to_date('2015/07/13','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1136,31,'MF','BASTIAN SCHWEINSTEIGER','GERMANY',to_date('2015/07/13','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (111,1137,36,'DF','MATTEO DARMIAN','ITALY',to_date('2015/07/11','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2221,null,'GK','JOEL CASTRO PEREIRA','SWITZERLAND',to_date('2012/07/11','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2222,null,'GK','KIERAN O''HARA','ENGLAND',to_date('2012/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2223,null,'GK','DEAN HENDERSON','ENGLAND',to_date('2013/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2224,null,'DF','MATT OLOSUNDE','USA',to_date('2016/03/11','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2225,null,'DF','AXEL TUANZEBE','CONGO',to_date('2013/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2226,null,'DF','REGAN POOLE','CARDIFF',to_date('2015/09/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2227,null,'DF','CHARLIE SCOTT','ENGLAND',to_date('2014/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2228,null,'DF','SADIQ EL FITOURL','LIBYA',to_date('2015/01/30','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2229,null,'DF','JOE RILEY','ENGLAND',to_date('2013/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2230,null,'MF','SCOTT MCTOMINAY','ENGLAND',to_date('2013/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2231,null,'MF','TOSIN KEHINDE','NIGERIA',to_date('2014/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2232,null,'MF','JOSH HARROP','ENGLAND',to_date('2012/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2233,null,'MF','SEAN GOSS','GERMANY',to_date('2012/07/11','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2234,null,'MF','DEVONTE REDMOND','ENGLAND',to_date('2013/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2235,null,'MF','MATTY WILLOCK','ENGLAND',to_date('2012/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2236,null,'FW','DEMETRI MITCHELL','ENGLAND',to_date('2013/07/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (222,2237,null,'FW','JOSH DOUGHTY','CANADA',to_date('2015/01/01','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (333,3331,null,'MANAGER','JOSE MOURINHO','PORTUGAL',to_date('2016/05/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (333,3332,null,'ASSISTANT MANAGER','RUI FARIA','PORTUGAL',to_date('2016/05/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (333,3333,null,'COACH','SILVINO LOURO','PORTUGAL',to_date('2016/05/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (333,3334,null,'COACH','RICARDO FORMOSINHO','PORTUGAL',to_date('2016/05/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (333,3335,null,'COACH','CARLOS LALIN','SPAIN',to_date('2016/05/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (333,3336,null,'GOALKEEPING COACH','EMILIO ALVAREZ','SPAIN',to_date('2016/05/27','YYYY/MM/DD'));
Insert into PLAYERS (IDNO,MEMBERNO,BACKNUMBER,POSITION,NAME,NATIONALITY,DATEOFJOIN) values (333,3337,null,'ANALYST','GIOVANNI CERRA','ENGLAND',to_date('2016/05/27','YYYY/MM/DD'));

commit;